apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-innstillinger
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 7070
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-innstillinger/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-innstillinger/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-innstillinger/internal/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app-q0.adeo.no/modiapersonoversikt-innstillinger
    - https://app-q1.adeo.no/modiapersonoversikt-innstillinger
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt-q0
          namespace: personoversikt
          cluster: dev-fss
        - application: modiapersonoversikt-q1
          namespace: personoversikt
          cluster: dev-fss
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://b27dbvl013.preprod.local:5432/modiapersonoversikt-innstillinger"
    - name: VAULT_MOUNTPATH
      value: "postgresql/preprod-fss"
