apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-innstillinger
  namespace: default
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 7070
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-innstillinger/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-innstillinger/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-innstillinger/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modiapersonoversikt-innstillinger.nais.preprod.local
    - https://app-q0.adeo.no/modiapersonoversikt-innstillinger
    - https://app-q1.adeo.no/modiapersonoversikt-innstillinger
    - https://app-q6.adeo.no/modiapersonoversikt-innstillinger
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: ISSO_JWKS_URL
      value: "https://isso-q.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: ISSO_ISSUER
      value: "https://isso-q.adeo.no:443/isso/oauth2"
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://b27dbvl013.preprod.local:5432/modiapersonoversikt-innstillinger"
    - name: VAULT_MOUNTPATH
      value: "postgresql/preprod-fss"
