apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-innstillinger
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 7070
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-innstillinger/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-innstillinger/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-innstillinger/internal/metrics
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app.adeo.no/modiapersonoversikt-innstillinger
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 65
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-fss
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - name: ISSO_JWKS_URL
      value: "https://isso.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: ISSO_ISSUER
      value: "https://isso.adeo.no:443/isso/oauth2"
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://A01DBVL009.adeo.no:5432/modiapersonoversikt-innstillinger"
    - name: VAULT_MOUNTPATH
      value: "postgresql/prod-fss"
