apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-innstillinger
  namespace: default
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 7070
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-innstillinger/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-innstillinger/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-innstillinger/metrics
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://modiapersonoversikt-innstillinger.nais.adeo.no
    - https://app.adeo.no/modiapersonoversikt-innstillinger
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 65
  vault:
    enabled: true
  env:
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://A01DBVL009.adeo.no:5432/modiapersonoversikt-innstillinger"
    - name: VAULT_MOUNTPATH
      value: "postgresql/prod-fss"
